# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hwXqJfJnbsAlAK2HQ83B1RuC2sI8twnw
"""

import random

# Questions database
questions = {

       "mathematics": {
        "easy": {
            "What is 2 + 3?": "5",
            "What is 12 - 6?": "6",
            "What is 9 * 2?": "18"
        },
        "medium": {
            "What is 36 / 4?": "9",
            "What is the square root of 81?": "9",
            "What is 15 % 2?": "1"
        },
        "hard": {
            "What is 2^11?": "2048",
            "What is the derivative of x^2?": "2x",
            "What is the integral of 1/x dx?": "ln|x| + C"
        }
    },
    "science": {
        "easy": {
            "What planet is known as the Red Planet?": "Mars",
            "What is H2O more commonly known as?": "Water",
            "How many continents are there?": "7"
        },
        "medium": {
            "What gas do plants absorb from the atmosphere?": "Carbon dioxide",
            "What is the hardest natural substance on Earth?": "Diamond",
            "Who is known as the father of physics?": "Isaac Newton"
        },
        "hard": {
            "What is the speed of light in vacuum?": "299,792,458 meters per second",
            "Who developed the periodic table?": "Dmitri Mendeleev",
            "What is the powerhouse of the cell?": "Mitochondria"
        }
    }
}

def quiz_game():
    print("Welcome to the Quiz Game!")
    name = input("Enter your name: ")

    print(f"Hello, {name}! Choose a topic: mathematics or science")
    topic = input("Topic: ").lower()

    if topic not in questions:
        print("Invalid topic. Please choose mathematics or science.")
        return

    print(f"Choose a difficulty level: easy, medium, or hard")
    difficulty = input("Difficulty: ").lower()

    if difficulty not in questions[topic]:
        print("Invalid difficulty level. Please choose easy, medium, or hard.")
        return

    score = 0
    questions_list = list(questions[topic][difficulty].items())
    random.shuffle(questions_list)

    for question, answer in questions_list:
        user_answer = input(f"Question: {question}\nYour answer: ")
        if user_answer.strip().lower() == answer.strip().lower():
            print("Correct!")
            score += 1
        else:
            print(f"Incorrect. The correct answer is: {answer}")

    print(f"Your final score is: {score}/{len(questions[topic][difficulty])}")
    print("Thank you for playing the Quiz Game!")

# Run the quiz game
quiz_game()